//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI_Test_Software {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class app : global::System.Configuration.ApplicationSettingsBase {
        
        private static app defaultInstance = ((app)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new app())));
        
        public static app Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Seagull\\BarTender\\8.0")]
        public string BarTenderExePath {
            get {
                return ((string)(this["BarTenderExePath"]));
            }
            set {
                this["BarTenderExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\SmartRFProgConsole.exe")]
        public string CC2510FlashTool {
            get {
                return ((string)(this["CC2510FlashTool"]));
            }
            set {
                this["CC2510FlashTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\medsense_label_form.btw")]
        public string MedSenseLabelFormFileName {
            get {
                return ((string)(this["MedSenseLabelFormFileName"]));
            }
            set {
                this["MedSenseLabelFormFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\temp_print_file.txt")]
        public string TempPrintFile {
            get {
                return ((string)(this["TempPrintFile"]));
            }
            set {
                this["TempPrintFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Test_List")]
        public string TestListFolder {
            get {
                return ((string)(this["TestListFolder"]));
            }
            set {
                this["TestListFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Texas Instruments\\SmartRF Tools\\Flash Programmer\\bin")]
        public string CC2510FlashToolPath {
            get {
                return ((string)(this["CC2510FlashToolPath"]));
            }
            set {
                this["CC2510FlashToolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\bartend.exe")]
        public string BarTenderExe {
            get {
                return ((string)(this["BarTenderExe"]));
            }
            set {
                this["BarTenderExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test Name:")]
        public string TagTestFlowName {
            get {
                return ((string)(this["TagTestFlowName"]));
            }
            set {
                this["TagTestFlowName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Completed Product:")]
        public string TagCompleteNum {
            get {
                return ((string)(this["TagCompleteNum"]));
            }
            set {
                this["TagCompleteNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fail Product:")]
        public string TagFailNum {
            get {
                return ((string)(this["TagFailNum"]));
            }
            set {
                this["TagFailNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fail Product:")]
        public string TagPassNum {
            get {
                return ((string)(this["TagPassNum"]));
            }
            set {
                this["TagPassNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Test_Result")]
        public string TestResultFolder {
            get {
                return ((string)(this["TestResultFolder"]));
            }
            set {
                this["TestResultFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Hardware_Cfg")]
        public string HardwareCfgFolder {
            get {
                return ((string)(this["HardwareCfgFolder"]));
            }
            set {
                this["HardwareCfgFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CONNECTOR_0.txt")]
        public string Connector0FileName {
            get {
                return ((string)(this["Connector0FileName"]));
            }
            set {
                this["Connector0FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CONNECTOR_1.txt")]
        public string Connector1FileName {
            get {
                return ((string)(this["Connector1FileName"]));
            }
            set {
                this["Connector1FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pin\ttype\tnum\tpolarity\trange")]
        public string HardwareCfgHeadline {
            get {
                return ((string)(this["HardwareCfgHeadline"]));
            }
            set {
                this["HardwareCfgHeadline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Test_Result_Template")]
        public string TestResultTemplateFolder {
            get {
                return ((string)(this["TestResultTemplateFolder"]));
            }
            set {
                this["TestResultTemplateFolder"] = value;
            }
        }
    }
}
